### PR TITLE
Create showcase.md

### PR DESCRIPTION
**Pull request by rstacruz**
Don't know how to format (or to name) this section at the moment, but here we go... that's a start. Please add some more if you know any. :)

### CODE REVIEW

**Comment by knownasilya** [comment]
I added a link from the readme. Not sure if that's the best place (maybe last?), would love to see what it looks like but busy at the moment.

**Comment by rstacruz** [comment]
Ah... getting more in there. I split them up into 2 sections to make it a bit more inviting to read through.

**Comment by knownasilya** [comment]
I like the split.

**Comment by rstacruz** [comment]
Okay, this should be good enough to have on the site itself for now. We can add more later!

Great work. Thank you all for your contributions. 💚

**Pull request merged**
